In [2]:
import pandas as pd

In [7]:
customers = pd.read_csv("../clean/customers.csv", dtype = {"customer_zip_code_prefix" : str})

In [3]:
geolocation = pd.read_csv("../clean/geolocation.csv", dtype={"geolocation_zip_code_prefix": str})

In [9]:
order_items = pd.read_csv("../clean/order_items.csv")

In [10]:
orders = pd.read_csv("../clean/orders.csv")

In [11]:
payments = pd.read_csv("../clean/payments.csv")

In [12]:
product_category = pd.read_csv("../clean/product_category.csv")

In [13]:
products = pd.read_csv("../clean/products.csv")

In [14]:
reviews = pd.read_csv("../clean/reviews.csv")

In [15]:
sellers = pd.read_csv("../clean/sellers.csv", dtype={"seller_zip_code_prefix": str})

In [16]:
tables = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "orders": orders,
    "payments": payments,
    "product_category": product_category,
    "products": products,
    "reviews": reviews,
    "sellers": sellers
}

In [17]:
for name,df in tables.items() :
    print(f"\n{name} : ")
    print(df.head())

customers :
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

  customer_zip_code_prefix          customer_city customer_state
0                    14409                 Franca             SP
1                    09790  Sao Bernardo Do Campo             SP
2                    01151              Sao Paulo             SP
3                    08775        Mogi Das Cruzes             SP
4                    13056               Campinas             SP

geolocation :
  geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                       01001       -23.550227       -46.634039
1                       01002       -23.547657       -46.634991
2                       01003       -23.549000       -46.635582
3                       01004       -23.549829       -46.634792
4                       01005       -23.549547       -46.636406

  geolocation_city geolocation_state
0        Sao Paulo                SP
1        Sao Paulo                SP
2        Sao Paulo                SP
3        Sao Paulo                SP
4        Sao Paulo                SP

order_items :
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

orders :
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0                    2017-10-18
1                    2018-08-13
2                    2018-09-04
3                    2017-12-15
4                    2018-02-26

payments :
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

product_category :
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

products :
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

reviews :
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score                             review_comment_message  \
0             4                                         No Comment
1             5                                         No Comment
2             5                                         No Comment
3             5              Recebi bem antes do prazo estipulado.
4             5  Parabéns lojas lannister adorei comprar pela I...

  review_creation_date review_answer_timestamp review_sentiment
0  2018-01-18 00:00:00     2018-01-18 21:46:59         Positive
1  2018-03-10 00:00:00     2018-03-11 03:05:13         Positive
2  2018-02-17 00:00:00     2018-02-18 14:36:24         Positive
3  2017-04-21 00:00:00     2017-04-21 22:02:06         Positive
4  2018-03-01 00:00:00     2018-03-02 10:26:53         Positive

sellers :
                          seller_id seller_zip_code_prefix        seller_city  \
0  3442f8959a84dea7ee197c632cb2df15                  13023           Campinas
1  d1b65fc7debc3361ea86b5f14c68d2e2                  13844         Mogi Guacu
2  ce3ad9de960102d0677a81f5d0bb7b2d                  20031     Rio De Janeiro
3  c0f3eea2e14555b6faeea3dd58c1b1c3                  04195          Sao Paulo
4  51a04a8a6bdcb23deccc82b0b80742cf                  12914  Braganca Paulista

  seller_state
0           SP
1           SP
2           RJ
3           SP
4           SP

# DIM CUSTOMERS

In [20]:
customers.head(1)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP

In [21]:
geolocation.head(1)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01001,-23.550227,-46.634039,Sao Paulo,SP